platform: Any CPU

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: NLog.Targets.Sentry.Core.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
