platform: Any CPU
configuration: Release

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - dotnet build -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
  - dotnet pack "src/NLog.Targets.Sentry.Core/NLog.Targets.Sentry.Core.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
  - path: artifacts\**\*.*